# Generated by Django 5.2 on 2025-05-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('G', 'General'), ('D', 'Detail')], max_length=1)),
                ('level', models.IntegerField()),
                ('induk', models.CharField(blank=True, max_length=50, null=True)),
                ('satuan', models.CharField(blank=True, max_length=20, null=True)),
                ('qty_stok', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pemasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_po', models.CharField(max_length=50, unique=True)),
                ('tanggal', models.DateField()),
                ('alamat_kirim', models.TextField()),
                ('qty_po', models.PositiveIntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qty_terima', models.PositiveIntegerField(default=0)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_barang.gudang')),
                ('kode_barang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_barang.barang')),
                ('pemasok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_barang.pemasok')),
            ],
        ),
        migrations.CreateModel(
            name='TerimaBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_terima', models.CharField(max_length=50, unique=True)),
                ('tanggal', models.DateField()),
                ('pemasok', models.CharField(max_length=100)),
                ('gudang', models.CharField(max_length=100)),
                ('kode_barang', models.CharField(max_length=100)),
                ('qty_terima', models.PositiveIntegerField()),
                ('nomor_po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_barang.po')),
            ],
        ),
    ]
