# Generated by Django 5.2 on 2025-05-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_barang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
