# Generated by Django 5.2 on 2025-05-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_barang', '0002_barang_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
